### ISSUE TITLE
Serving files from a CDN

### ISSUE THREAD

**Issue by abitdodgy** [rzane/upload#1]
How would one go about serving files via CDN? Does it require any extra configuration or is that transparent to this lib?

**Comment by rzane** [comment]
If you're using the local adapter, you can just set the `:public_path` to an absolute URL:

```elixir
config :upload, Upload, adapter: Upload.Adapters.Local
config :upload, Upload.Adapters.Local, public_path: "https://mycdn.com"
```

See: https://github.com/rzane/upload/blob/f09dc7cb2778c2758d2cd0713d56327d5e6e195c/lib/upload/adapters/local.ex#L32

---

If you're using the S3 adapter, there is an undocumented `:uri` configuration:

```elixir
config :upload, Upload, adapter: Upload.Adapters.S3
config :upload, Upload.Adapters.S3, bucket: "your_bucket_name", uri: "https://mycdn.com"
```

See: https://github.com/rzane/upload/blob/f09dc7cb2778c2758d2cd0713d56327d5e6e195c/lib/upload/adapters/s3.ex#L31
