### ISSUE TITLE
Validation strategy

### ISSUE THREAD

**Issue by abitdodgy** [rzane/upload#2]
What validation strategy do you use with this lib? I know the API is minimal, but do we have to rely on plug config to validate file size and packet size? How about formats and so on?

**Comment by rzane** [comment]
This is where the [`Upload.Uploader`](https://hexdocs.pm/upload/Upload.Uploader.html) behaviour comes in to play.

```elixir
defmodule MyApp.LogoUploader do
  use Upload.Uploader

  @impl true
  def cast(file) do
    with {:ok, upload} <- Upload.cast(file) do
      extension = Upload.get_extension(upload)

      if Enum.member?(~w(.png), extension) do
        {:ok, upload}
      else
        {:error, "not a valid file extension"}
      end
    end
  end
end
```

Now, instead of using the `Upload` module, you'll use `MyApp.LogoUploader` instead.

**Comment by rzane** [comment]
Thank you for calling out the things I didn't clarify in the readme. The documentation could definitely use some work 😄.

**Comment by rzane** [comment]
Oh, and you have access to `upload.path` in the above example if you wanted to read or stat the file before uploading.

**Comment by abitdodgy** [comment]
Thanks for all the information. I'll take it for a spin in a new app I'm working on. File uploads are such a pain that I am tempted to with a service like Cloudinary, but the minimal API of this lib is appealing to me.

**Comment by rzane** [comment]
Great! Let me know how it works out. Feel free to send feedback!

**Comment by jhonathas** [comment]
Hello, sorry to come back in a closed issue, but I was not sure where to use the validation strategy. How should I use this module? No changeset?

**Comment by jhonathas** [comment]
I got it, is that the cast function from inside my uploader needs to have 2 parameters, I had put it as in the documentation, only 1, and it did not work.
