### ISSUE TITLE
Splitting upload key - easier way than re-implementing do_cast with my own Uploader?

### ISSUE THREAD

**Issue by theangryangel** [rzane/upload#3]
First off, thank you very very much for open sourcing your implementation of file uploading. I was on my way to implementing something that was turning out very similar and honestly your implementation is just much better.

With the local adapter I'm a little worried with the number of files that will end up in the directory for my project. What I've done in other projects is take the key (using Upload terminology) and then take the first 9 characters off the uuid, split them by the path separator and then join then path together, ending up with something like `000/000/000/0000000000.ext`

I know I can do this with my own uploader implementation by overriding the relevant cast functions. Is there an alternative I've missed, without resorting to patching the project? Seems like a lot of work for what is effectively just overriding the `generate_key` function.

Thanks <3

**Comment by rzane** [comment]
Does the prefix option for [`generate_key`](https://hexdocs.pm/upload/Upload.html#generate_key/2) meet your need?

Since you're basically just looking to prepend a random directory name to the path, could you just say:

```elixir
prefix = Ecto.UUID.generate() |> String.split("-")
Upload.cast(whatever, prefix: prefix)
```

If not, I suppose we could make `generate_key` overridable, allowing you to provide your own custom implementation, but I'd like to avoid that if possible.

**Comment by theangryangel** [comment]
I already namespace them by the parent record, and where it's convenient I also use the parent record ID as part of the prefix, but it's not always convenient to have the persisted the record in some cases. Hadn't occured to me to just add a bit more on top as well. Not sure why. Thanks.
