### ISSUE TITLE
field upload is invalid when sending from the frontend app.

### ISSUE THREAD

**Issue by aislanmaia** [rzane/upload#4]
I'm using the frontend separated from the backend (Vue application). 
And I don't know what the fields I have to send to changeset validation.

I'm sending this:
```
  let fd = new FormData()
  fd.append('customer[avatar][filename]', params.avatar.name)
  fd.append('customer[avatar][key]', params.avatar.name)
  fd.append('customer[avatar][path]', '/avatar/'
```
This sends something like this in the params:
```
%{"customer" => %{"avatar" => %{"content_type" => "image/jpeg", "filename" => "3x4.jpg", "key" => "3x4.jpg", "path" => "/avatar/"}  ......... more fields }
```
In my response I'm receiving:
```
errors: {avatar: ["is invalid"]}
```
But no explicit message to what is wrong and what is expected to be sended to the server.

What the fields image file needs to have?

**Comment by aislanmaia** [comment]
Now, if I just do this:

```
fd.append('customer[avatar]', params.avatar)
```

and in my params sended to phoenix this is logged out into console:
```
[debug] Processing with ApiWeb.Store.CustomerController.create/2                                                                                                                             
  Parameters: %{"customer" => %{"avatar" => "[object Object]", "cpf" => "96416076268", "name" => "Aislan", "phone" => "89999762292"}}                                                        
  Pipelines: [:api, :jwt_authenticated] 
```
As you can see, "[object Object]" is there, and the validation passes, but upload doesn't work.

**Comment by rzane** [comment]
I recommend taking a look at https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects.

The HTML `<input type="file" />` has a `.files` property that will give you a list of `File` instances. You need to send one of those to the server in the FormData:

``` html
<input type="file" id="avatar" />
```

```javascript
const input = document.getElementById('avatar');
const formData = new FormData();
formData.attach('customer[avatar]', input.files[0]);
```

In Vue, you can get the `File` instance by using a custom `input` handler:

```vue
<input type="file" @input="handleAvatarInput($event.target.files[0])" />
```

**Comment by aislanmaia** [comment]
Thanks @rzane . I was trying to get the File instance from a <q-uploader> component of Quasar framework. What seems to have happened was that the instance wasn't the correct one that FormData and Phoenix expects.

**Comment by rzane** [comment]
I hope that helps! Let me know if you run into any more issues.
