### ISSUE TITLE
How to destroy an object on S3?

### ISSUE THREAD

**Issue by tporto** [rzane/upload#7]

**Comment by rzane** [comment]
You'll have to use ExAws directly for that. Alternatively, there's this adapter-based library that I created: https://github.com/rzane/file_store.

I intended to update this library to depend on FileStore, but I haven't gotten around to it.

**Comment by tporto** [comment]
> You'll have to use ExAws directly for that. Alternatively, there's this adapter-based library that I created: https://github.com/rzane/file_store.
> 
> I intended to update this library to depend on FileStore, but I haven't gotten around to it.

So can I use File_store instead of Upload?

**Comment by rzane** [comment]
Yes, FileStore is for interacting with different storage providers. Upload allows you to accept a file upload and save a reference to it in your database. There's some overlap, but each has functionality that the other one doesn't.
